name: Send Telegram Notification

on:
  push:
    branches:
      - main

jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Print Telegram Secrets
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          echo "::add-mask::$TELEGRAM_BOT_TOKEN"
          echo "::add-mask::$TELEGRAM_CHAT_ID"
          echo "Telegram Bot Token: $TELEGRAM_BOT_TOKEN"
          echo "Telegram Chat ID: $TELEGRAM_CHAT_ID"

      - name: Telegram Notification
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          PRODUCT_NAME: YourProductName
          DISTRIB_REVISION: YourRevision
          KERNEL_PATCHVER: YourKernelPatchver
          FILE_TIME1: YourFileTime1
          BUILD_TIME: YourBuildTime
          GITHUB_RELEASE: YourGithubRelease
        run: |
          # Print the curl command for debugging
          echo "curl -X POST 'https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage' -d 'chat_id=${TELEGRAM_CHAT_ID}' -d 'text=æ‚¨çš„${PRODUCT_NAME}å›ºä»¶æˆåŠŸç¼–è¯‘å®Œæˆäº†ï¼%0A%0AğŸ›  ç¼–è¯‘ç‰ˆæœ¬ï¼š${DISTRIB_REVISION}%0AğŸ–¥ å†…æ ¸ç‰ˆæœ¬ï¼š${KERNEL_PATCHVER}%0AğŸˆ ç¼–è¯‘æ—¶é—´ï¼š${FILE_TIME1}%0Aâ° ç¼–è¯‘ç”¨æ—¶ï¼š${BUILD_TIME}%0AğŸ‰ å‘å¸ƒåœ°å€ï¼š${GITHUB_RELEASE}%0AğŸŒ´ å›ºä»¶å·²ç»ç¼–è¯‘å®Œæˆ ğŸˆï¼ï¼ï¼'"
          # Execute the curl command
          curl -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d "chat_id=${TELEGRAM_CHAT_ID}" \
            -d "text=æ‚¨çš„${PRODUCT_NAME}å›ºä»¶æˆåŠŸç¼–è¯‘å®Œæˆäº†ï¼%0A%0AğŸ›  ç¼–è¯‘ç‰ˆæœ¬ï¼š${DISTRIB_REVISION}%0AğŸ–¥ å†…æ ¸ç‰ˆæœ¬ï¼š${KERNEL_PATCHVER}%0AğŸˆ ç¼–è¯‘æ—¶é—´ï¼š${FILE_TIME1}%0Aâ° ç¼–è¯‘ç”¨æ—¶ï¼š${BUILD_TIME}%0AğŸ‰ å‘å¸ƒåœ°å€ï¼š${GITHUB_RELEASE}%0AğŸŒ´ å›ºä»¶å·²ç»ç¼–è¯‘å®Œæˆ ğŸˆï¼ï¼ï¼"
