name: Send Telegram Notification

on:
  push:
    branches:
      - main

jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Set environment variables
        run: |
          echo "PRODUCT_NAME=YourProductName" >> $GITHUB_ENV
          echo "DISTRIB_REVISION=YourRevision" >> $GITHUB_ENV
          echo "KERNEL_PATCHVER=YourKernelPatchver" >> $GITHUB_ENV
          echo "FILE_TIME1=YourFileTime1" >> $GITHUB_ENV
          echo "BUILD_TIME=YourBuildTime" >> $GITHUB_ENV
          echo "GITHUB_RELEASE=YourGithubRelease" >> $GITHUB_ENV

      - name: Print Telegram Secrets
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          echo "Telegram Bot Token: $TELEGRAM_BOT_TOKEN"
          echo "Telegram Chat ID: $TELEGRAM_CHAT_ID"

      - name: Telegram notification
        run: |
          curl "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d "text=æ‚¨çš„${{ env.PRODUCT_NAME }}å›ºä»¶æˆåŠŸç¼–è¯‘å®Œæˆäº†ï¼%0A%0AðŸ›  ç¼–è¯‘ç‰ˆæœ¬ï¼š${{ env.DISTRIB_REVISION }}%0AðŸ–¥ å†…æ ¸ç‰ˆæœ¬ï¼š${{ env.KERNEL_PATCHVER }}%0AðŸŽˆ ç¼–è¯‘æ—¶é—´ï¼š${{ env.FILE_TIME1 }}%0Aâ° ç¼–è¯‘ç”¨æ—¶ï¼š${{ env.BUILD_TIME }}%0AðŸŽ‰ å‘å¸ƒåœ°å€ï¼š${{ env.GITHUB_RELEASE }}%0AðŸŒ´ å›ºä»¶å·²ç»ç¼–è¯‘å®Œæˆ ðŸŽˆï¼ï¼ï¼" \
            >/dev/null 2>&1 && echo "ok..."
